{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dockerfiler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dockerfiler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dockerfiler/dockerfiler_{{ version }}.tar.gz
  sha256: a9f0c02ee7993d94944a9e0a20490743ec7e5961126253f2322b2f38dac6b12b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.5.0
    - r-attempt >=0.3.1
    - r-cli >=2.3.0
    - r-desc >=1.2.0
    - r-fs >=1.5.0
    - r-glue >=1.4.2
    - r-jsonlite >=1.7.2
    - r-memoise
    - r-pak >=0.2.0
    - r-pkgbuild >=1.2.0
    - r-remotes >=2.2.0
    - r-usethis >=2.0.1
  run:
    - r-base
    - r-r6 >=2.5.0
    - r-attempt >=0.3.1
    - r-cli >=2.3.0
    - r-desc >=1.2.0
    - r-fs >=1.5.0
    - r-glue >=1.4.2
    - r-jsonlite >=1.7.2
    - r-memoise
    - r-pak >=0.2.0
    - r-pkgbuild >=1.2.0
    - r-remotes >=2.2.0
    - r-usethis >=2.0.1

test:
  commands:
    - $R -e "library('dockerfiler')"           # [not win]
    - "\"%R%\" -e \"library('dockerfiler')\""  # [win]

about:
  home: https://github.com/ThinkR-open/dockerfiler
  license: MIT
  summary: Build a Dockerfile straight from your R session. 'dockerfiler' allows you to create step by step a Dockerfile, and provide convenient tools to wrap R code inside this Dockerfile.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
