{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dockerfiler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dockerfiler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dockerfiler/dockerfiler_{{ version }}.tar.gz
  sha256: 77cbbb05265b22c7fdd5fba06caf294fc3f02c4f92faefa3102f57d9c6a9bd5a

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.5.0
    - r-attempt >=0.3.1
    - r-cli >=2.3.0
    - r-desc >=1.2.0
    - r-fs >=1.5.0
    - r-glue >=1.4.2
    - r-jsonlite >=1.7.2
    - r-pak >=0.2.0
    - r-pkgbuild >=1.2.0
    - r-remotes >=2.2.0
    - r-renv >=0.12.0
    - r-usethis >=2.0.1
  run:
    - r-base
    - r-r6 >=2.5.0
    - r-attempt >=0.3.1
    - r-cli >=2.3.0
    - r-desc >=1.2.0
    - r-fs >=1.5.0
    - r-glue >=1.4.2
    - r-jsonlite >=1.7.2
    - r-pak >=0.2.0
    - r-pkgbuild >=1.2.0
    - r-remotes >=2.2.0
    - r-renv >=0.12.0
    - r-usethis >=2.0.1

test:
  commands:
    - $R -e "library('dockerfiler')"           # [not win]
    - "\"%R%\" -e \"library('dockerfiler')\""  # [win]

about:
  home: https://github.com/ColinFay/dockerfiler
  license: MIT
  summary: Build a Dockerfile straight from your R session. 'dockerfiler' allows you to create step by step a Dockerfile, and provide convenient tools to wrap R code inside this Dockerfile.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dockerfiler
# Title: Easy Dockerfile Creation from R
# Version: 0.1.3
# Authors@R: person('Colin', 'Fay', email = 'contact@colinfay.me', role = c('cre', 'aut'))
# Description: Build a Dockerfile straight from your R session. 'dockerfiler' allows you to create step by step a Dockerfile, and provide convenient tools to wrap R code inside this Dockerfile.
# License: MIT + file LICENSE
# URL: https://github.com/ColinFay/dockerfiler
# BugReports: https://github.com/ColinFay/dockerfiler/issues
# Imports: attempt, glue, R6, utils
# Suggests: covr, testthat, knitr, rmarkdown
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-19 15:32:05 UTC; colin
# Author: Colin Fay [cre, aut]
# Maintainer: Colin Fay <contact@colinfay.me>
# Repository: CRAN
# Date/Publication: 2019-03-19 16:10:03 UTC
