bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: qh4dmuntvO5Qh1Zvo2lvufgIVyJACcWexcUvLsC6q9fkFyQ34HCrtNtq1d1rREWt1Sj5BnZ6EKt9pu4BzNhss0PquamAIUPKiq4snVbh3GvixPoRVIAYT6FUM+mk/bfuS3QDRA55JRerLn0oYyy/EybbZM0W+VDx2/Cy8CuRwnqGEKk3Q6u3Gu/aLQrv6WuRXHYqDYexNBJI2OAxDxYo/8Qr2KCSdigoLd4jtLfteBU/EbmbUF2EU3046ft5wq9DBznA/KUkmXb3WPiUf+S3NOwbVAx+rX1suCkb7rccwKPCPN/C346+Nb+JceYfRaSqXsaL0lzvTLwrQcXSxYRgNrbLkT+NgPSDCgOfM5UYTI5XWF9N0VtmpVOkNDw4S7YweWAzcC1QlFI8Y4A0KcoyP6kL8wo/dDLrMK/hK6ZxYhLaak3WJE6+p+Ge9QK5tjVl9LOqWAb0SwWwXoFFfZsnfhzg8z7Gi7MiWcd8VzNUWysBVz0nzGvx15OAckT6wquwbwSydAuYGma2INBgdvaZeMPNcYtMF/G0hjM1LkOLTlWX+WO4HpRfPLJdBdE2GjRPMaRDhPO+lxUs+9kdoeEqHsf/bbTt4ox0LZdJBTen3xCOQTtG6xxliPl4uxTtu2spqbyaHO9Yn0eTWdQU27MvLIqJDdloGNoxpshDzmTjf08=
conda_forge_output_validation: true
